import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite-plus";

const isTauri = !!globalThis.process?.env?.TAURI_ENV_PLATFORM;

export default defineConfig({
  fmt: {},
  lint: {
    plugins: ["oxc", "typescript", "unicorn", "react"],
    categories: {
      correctness: "warn",
    },
    env: {
      builtin: true,
    },
    ignorePatterns: ["dist"],
    overrides: [
      {
        files: ["**/*.{ts,tsx}"],
        rules: {
          "constructor-super": "error",
          "for-direction": "error",
          "getter-return": "error",
          "no-async-promise-executor": "error",
          "no-case-declarations": "error",
          "no-class-assign": "error",
          "no-compare-neg-zero": "error",
          "no-cond-assign": "error",
          "no-const-assign": "error",
          "no-constant-binary-expression": "error",
          "no-constant-condition": "error",
          "no-control-regex": "error",
          "no-debugger": "error",
          "no-delete-var": "error",
          "no-dupe-class-members": "error",
          "no-dupe-else-if": "error",
          "no-dupe-keys": "error",
          "no-duplicate-case": "error",
          "no-empty": "error",
          "no-empty-character-class": "error",
          "no-empty-pattern": "error",
          "no-empty-static-block": "error",
          "no-ex-assign": "error",
          "no-extra-boolean-cast": "error",
          "no-fallthrough": "error",
          "no-func-assign": "error",
          "no-global-assign": "error",
          "no-import-assign": "error",
          "no-invalid-regexp": "error",
          "no-irregular-whitespace": "error",
          "no-loss-of-precision": "error",
          "no-misleading-character-class": "error",
          "no-new-native-nonconstructor": "error",
          "no-nonoctal-decimal-escape": "error",
          "no-obj-calls": "error",
          "no-prototype-builtins": "error",
          "no-redeclare": "error",
          "no-regex-spaces": "error",
          "no-self-assign": "error",
          "no-setter-return": "error",
          "no-shadow-restricted-names": "error",
          "no-sparse-arrays": "error",
          "no-this-before-super": "error",
          "no-undef": "error",
          "no-unexpected-multiline": "error",
          "no-unreachable": "error",
          "no-unsafe-finally": "error",
          "no-unsafe-negation": "error",
          "no-unsafe-optional-chaining": "error",
          "no-unused-labels": "error",
          "no-unused-private-class-members": "error",
          "no-unused-vars": "error",
          "no-useless-backreference": "error",
          "no-useless-catch": "error",
          "no-useless-escape": "error",
          "no-with": "error",
          "require-yield": "error",
          "use-isnan": "error",
          "valid-typeof": "error",
          "no-array-constructor": "error",
          "no-unused-expressions": "error",
          "typescript/ban-ts-comment": "error",
          "typescript/no-duplicate-enum-values": "error",
          "typescript/no-empty-object-type": "error",
          "typescript/no-explicit-any": "error",
          "typescript/no-extra-non-null-assertion": "error",
          "typescript/no-misused-new": "error",
          "typescript/no-namespace": "error",
          "typescript/no-non-null-asserted-optional-chain": "error",
          "typescript/no-require-imports": "error",
          "typescript/no-this-alias": "error",
          "typescript/no-unnecessary-type-constraint": "error",
          "typescript/no-unsafe-declaration-merging": "error",
          "typescript/no-unsafe-function-type": "error",
          "typescript/no-wrapper-object-types": "error",
          "typescript/prefer-as-const": "error",
          "typescript/prefer-namespace-keyword": "error",
          "typescript/triple-slash-reference": "error",
          "react/display-name": "error",
          "react/jsx-key": "error",
          "react/jsx-no-comment-textnodes": "error",
          "react/jsx-no-duplicate-props": "error",
          "react/jsx-no-target-blank": "error",
          "react/jsx-no-undef": "error",
          "react/no-children-prop": "error",
          "react/no-danger-with-children": "error",
          "react/no-direct-mutation-state": "error",
          "react/no-find-dom-node": "error",
          "react/no-is-mounted": "error",
          "react/no-render-return-value": "error",
          "react/no-string-refs": "error",
          "react/no-unescaped-entities": "error",
          "react/no-unknown-property": "error",
          "react/no-unsafe": "off",
          "react/react-in-jsx-scope": "off",
          "react/require-render-return": "error",
          "react/rules-of-hooks": "error",
          "react/exhaustive-deps": "warn",
          "react/only-export-components": [
            "error",
            {
              allowConstantExport: true,
            },
          ],
          "no-negated-condition": "off",
          "no-nested-ternary": "off",
          "unicorn/catch-error-name": "error",
          "unicorn/consistent-assert": "error",
          "unicorn/consistent-date-clone": "error",
          "unicorn/consistent-empty-array-spread": "error",
          "unicorn/consistent-existence-index-check": "error",
          "unicorn/consistent-function-scoping": "off",
          "unicorn/custom-error-definition": "off",
          "unicorn/empty-brace-spaces": "error",
          "unicorn/error-message": "error",
          "unicorn/escape-case": "error",
          "unicorn/explicit-length-check": "error",
          "unicorn/filename-case": "error",
          "unicorn/new-for-builtins": "error",
          "unicorn/no-abusive-eslint-disable": "error",
          "unicorn/no-accessor-recursion": "error",
          "unicorn/no-anonymous-default-export": "error",
          "unicorn/no-array-callback-reference": "error",
          "unicorn/no-array-for-each": "error",
          "unicorn/no-array-method-this-argument": "error",
          "unicorn/no-array-reduce": "off",
          "unicorn/no-array-reverse": "error",
          "unicorn/no-array-sort": "off",
          "unicorn/no-await-expression-member": "error",
          "unicorn/no-await-in-promise-methods": "error",
          "unicorn/no-console-spaces": "error",
          "unicorn/no-document-cookie": "error",
          "unicorn/no-empty-file": "error",
          "unicorn/no-hex-escape": "error",
          "unicorn/no-immediate-mutation": "error",
          "unicorn/no-instanceof-builtins": "error",
          "unicorn/no-invalid-fetch-options": "error",
          "unicorn/no-invalid-remove-event-listener": "error",
          "unicorn/no-lonely-if": "error",
          "unicorn/no-magic-array-flat-depth": "error",
          "unicorn/no-negated-condition": "error",
          "unicorn/no-negation-in-equality-check": "error",
          "unicorn/no-nested-ternary": "off",
          "unicorn/no-new-array": "error",
          "unicorn/no-new-buffer": "error",
          "unicorn/no-null": "off",
          "unicorn/no-object-as-default-parameter": "error",
          "unicorn/no-process-exit": "error",
          "unicorn/no-single-promise-in-promise-methods": "error",
          "unicorn/no-static-only-class": "error",
          "unicorn/no-thenable": "error",
          "unicorn/no-this-assignment": "error",
          "unicorn/no-typeof-undefined": "error",
          "unicorn/no-unnecessary-array-flat-depth": "error",
          "unicorn/no-unnecessary-array-splice-count": "error",
          "unicorn/no-unnecessary-await": "error",
          "unicorn/no-unnecessary-slice-end": "error",
          "unicorn/no-unreadable-array-destructuring": "error",
          "unicorn/no-unreadable-iife": "error",
          "unicorn/no-useless-collection-argument": "error",
          "unicorn/no-useless-error-capture-stack-trace": "error",
          "unicorn/no-useless-fallback-in-spread": "error",
          "unicorn/no-useless-length-check": "error",
          "unicorn/no-useless-promise-resolve-reject": "error",
          "unicorn/no-useless-spread": "error",
          "unicorn/no-useless-switch-case": "error",
          "unicorn/no-useless-undefined": "error",
          "unicorn/no-zero-fractions": "error",
          "unicorn/number-literal-case": "error",
          "unicorn/numeric-separators-style": "error",
          "unicorn/prefer-add-event-listener": "error",
          "unicorn/prefer-array-find": "error",
          "unicorn/prefer-array-flat": "error",
          "unicorn/prefer-array-flat-map": "error",
          "unicorn/prefer-array-index-of": "error",
          "unicorn/prefer-array-some": "error",
          "unicorn/prefer-at": "error",
          "unicorn/prefer-bigint-literals": "error",
          "unicorn/prefer-blob-reading-methods": "error",
          "unicorn/prefer-class-fields": "error",
          "unicorn/prefer-classlist-toggle": "error",
          "unicorn/prefer-code-point": "error",
          "unicorn/prefer-date-now": "error",
          "unicorn/prefer-default-parameters": "error",
          "unicorn/prefer-dom-node-append": "error",
          "unicorn/prefer-dom-node-dataset": "error",
          "unicorn/prefer-dom-node-remove": "error",
          "unicorn/prefer-dom-node-text-content": "error",
          "unicorn/prefer-event-target": "error",
          "unicorn/prefer-global-this": "error",
          "unicorn/prefer-includes": "error",
          "unicorn/prefer-keyboard-event-key": "error",
          "unicorn/prefer-logical-operator-over-ternary": "error",
          "unicorn/prefer-math-min-max": "error",
          "unicorn/prefer-math-trunc": "error",
          "unicorn/prefer-modern-dom-apis": "error",
          "unicorn/prefer-modern-math-apis": "error",
          "unicorn/prefer-module": "error",
          "unicorn/prefer-native-coercion-functions": "error",
          "unicorn/prefer-negative-index": "error",
          "unicorn/prefer-node-protocol": "error",
          "unicorn/prefer-number-properties": "error",
          "unicorn/prefer-object-from-entries": "error",
          "unicorn/prefer-optional-catch-binding": "error",
          "unicorn/prefer-prototype-methods": "error",
          "unicorn/prefer-query-selector": "error",
          "unicorn/prefer-reflect-apply": "error",
          "unicorn/prefer-regexp-test": "error",
          "unicorn/prefer-response-static-json": "error",
          "unicorn/prefer-set-has": "error",
          "unicorn/prefer-set-size": "error",
          "unicorn/prefer-spread": "error",
          "unicorn/prefer-string-raw": "error",
          "unicorn/prefer-string-replace-all": "error",
          "unicorn/prefer-string-slice": "error",
          "unicorn/prefer-string-starts-ends-with": "error",
          "unicorn/prefer-string-trim-start-end": "error",
          "unicorn/prefer-structured-clone": "error",
          "unicorn/prefer-ternary": "error",
          "unicorn/prefer-top-level-await": "error",
          "unicorn/prefer-type-error": "error",
          "unicorn/relative-url-style": "error",
          "unicorn/require-array-join-separator": "error",
          "unicorn/require-module-attributes": "error",
          "unicorn/require-module-specifiers": "error",
          "unicorn/require-number-to-fixed-digits-argument": "error",
          "unicorn/require-post-message-target-origin": "off",
          "unicorn/switch-case-braces": "error",
          "unicorn/text-encoding-identifier-case": "error",
          "unicorn/throw-new-error": "error",
          "react/no-multi-comp": "error",
        },
        env: {
          es2026: true,
          es2020: true,
          browser: true,
        },
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
  plugins: [react(), tailwindcss()],
  clearScreen: !isTauri,
  build: {
    outDir: isTauri ? "dist" : "../src/Claudio.Api/wwwroot",
    emptyOutDir: true,
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (
            id.includes("node_modules/react/") ||
            id.includes("node_modules/react-dom/") ||
            id.includes("node_modules/react-router/")
          ) {
            return "vendor";
          }
          if (id.includes("node_modules/@tanstack/")) {
            return "query";
          }
          if (id.includes("node_modules/@headlessui/")) {
            return "ui";
          }
        },
      },
    },
  },
  server: {
    strictPort: isTauri,
    proxy: isTauri
      ? undefined
      : {
          "/api": "http://localhost:8080",
          "/connect": "http://localhost:8080",
          "/images": "http://localhost:8080",
        },
  },
});
