services:
  claudio:
    image: ghcr.io/lmrisdal/claudio:latest
    ports:
      - "8080:8080"
    volumes:
      - claudio-data:/config
      - /path/to/games:/games:ro
    # environment:
    #   - CLAUDIO_IGDB_CLIENT_ID=
    #   - CLAUDIO_IGDB_CLIENT_SECRET=
    #   - CLAUDIO_PORT=8080

volumes:
  claudio-data:
